### ISSUE TITLE
build instructions

### ISSUE THREAD

**Issue by bwbohl** [oxygenxml/TEI-Facsimile-Plugin#9]
It would be nice to have some build instructions for this plugin

**Comment by bwbohl** [comment]
After successfully configuring maven profile (missing in SDK description) I run into the following error:

```
he project tei.customizations.plugin:customizations:1.0.0-SNAPSHOT (/Users/bwb/GitHub/bwbohl/TEI-Facsimile-Plugin/pom.xml) has 1 error
[ERROR]     Child module /SOME-PATH/TEI-Facsimile-Plugin/image-markup-plugin of /SOME-PATH/TEI-Facsimile-Plugin/pom.xml does not exist
```

how to proceed?

**Comment by AlexJitianu** [comment]
Hi,
At some point in the past I changed the project into a Maven Multiple Modules project. Now, I'm not sure it was a great idea since the second plugin is just a proof of concept for a Stand-off markup plugin that kept the markup  in a dedicated element. Nothing to do with facsimiles...

I made some changes in the project so you should be able to build. I will add some details on how to build the project as well.

**Comment by bwbohl** [comment]
thanks that helped!
